using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Entidad
{
    class PAR_EST_VAL_FILE
    {
        public int idPAR_EST_VAL_FILE { get; set; }
        public string PAR_EST_VAL_FILE_COD { get; set; }
        public string PAR_EST_VAL_FILE_DES { get; set; }
        public string PAR_EST_VAL_FILE_ESTL { get; set; }



    }
}
